apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xzmi43asx-python
  janus-idp.io/tekton: xzmi43asx-python
  backstage.io/kubernetes-id: xzmi43asx-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xzmi43asx-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
