apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xzmi43asx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xzmi43asx-python 
  name: xzmi43asx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xzmi43asx-python 
